---
  openapi: "3.0.0"
  servers:
    - url: https://akzz-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.luna.akamaiapis.net/papi/v1
  info:
    title: "Edge hostnames"
    version: v1
  paths:
    /edgehostnames:
      get:
        summary: List edge hostnames
        description: |
          This lists all edge hostnames available under a contract. To assign any of these hostnames to a property, run [Update a property's hostnames](https://papi-akamai.readme.io/reference/propertiespropertyidversionspropertyversionhostnames#put_properties-propertyid-versions-propertyversion-hostnames). Use the [Edge Hostname API](https://developer.akamai.com/api/core_features/edge_hostnames/v1.html#getcertificatefortheedgehostname) (HAPI) to modify edge hostnames, or delete any that aren't currently assigned to an active property configuration.
        operationId: "GET_edgehostnames"
        responses:
          200:
            description: ""
            headers:
              X-Limit-Edgehostnames-Per-Contract-Limit:
                schema:
                  type: string
              X-Limit-Edgehostnames-Per-Contract-Remaining:
                schema:
                  type: string
            content:
              application/json:
                example:
                  accountId: act_1-1TJZFB
                  contractId: ctr_1-1TJZH5
                  groupId: grp_15225
                  edgeHostnames:
                    items:
                      - edgeHostnameId: ehn_895822
                        edgeHostnameDomain: "example.com.edgekey.net"
                        productId: prd_Alta
                        domainPrefix: "example.com"
                        domainSuffix: "edgekey.net"
                        status: "PENDING"
                        secure: true
                        ipVersionBehavior: "IPV4"
                      - edgeHostnameId: ehn_887436
                        edgeHostnameDomain: "example.com.edgesuite.net"
                        productId: prd_Alta
                        domainPrefix: "example.com"
                        domainSuffix: "edgesuite.net"
                        secure: false
                        ipVersionBehavior: "IPV4"
                schema:
                  $ref: "#/components/schemas/edgehostname-get-response"
        parameters:
          - $ref: "#/components/parameters/trait_usePrefixesHeader_PAPI-Use-Prefixes"
          - $ref: "#/components/parameters/trait_contractParamRequired_contractId"
          - $ref: "#/components/parameters/trait_groupParamRequired_groupId"
          - $ref: "#/components/parameters/trait_optionsParam_options"
      post:
        summary: Create a new edge hostname
        description: |
          This operation creates a new edge hostname. As detailed in the sections below, you can use three approaches to secure new edge hostnames: [Standard TLS](doc:standard-tls-edge-hostname), [Enhanced TLS](doc:enhanced-tls-edge-hostname), or a [Shared Certificate](doc:shared-certificate-edge-hostname). You can [assign a use case](doc:assign-a-use-case-to-an-edge-hostname) mapping profile to optimize the hostname to serve specific types of traffic. For more information, see [Create edge hostnames using PAPI](http://learn.akamai.com/en-us/api/learn_akamai/getting_started_with_akamai_developers/core_features/create_edgehostnames.html). Once the hostname is active, you can [Update a property's hostnames](https://papi-akamai.readme.io/reference/propertiespropertyidversionspropertyversionhostnames#put_properties-propertyid-versions-propertyversion-hostnames) to assign it to a property. After you [activate a property](https://papi-akamai.readme.io/reference/propertiespropertyidactivations#post_properties-propertyid-activations), modifying your DNS to map the origin hostname to the edge hostname ultimately enables traffic on the property. For details, see [Enable traffic for a new edge hostname](doc:enable-traffic-for-a-new-edge-hostname). Use the [Edge Hostname API](https://developer.akamai.com/api/core_features/edge_hostnames/v1.html#getcertificatefortheedgehostname) (HAPI) to modify edge hostnames, or delete any that aren't currently assigned to an active property configuration.
        operationId: "POST_edgehostnames"
        responses:
          201:
            description: ""
            headers:
              X-Limit-Edgehostnames-Per-Contract-Limit:
                schema:
                  type: string
              X-Limit-Edgehostnames-Per-Contract-Remaining:
                schema:
                  type: string
              Location:
                schema:
                  type: string
            content:
              application/json:
                example:
                  edgeHostnameLink: "/papi/v0/edgehostnames/ehn_1332?contractId=ctr_1-1TJZH5&grp_15225"
                schema:
                  $ref: "#/components/schemas/edgehostname-post-response"
        requestBody:
          required: true
          content:
            application/json:
              example:
                productId: prd_Dynamic_Site_Del
                domainPrefix: "www.example.com"
                domainSuffix: "edgesuite.net"
                secureNetwork: "STANDARD_TLS"
                ipVersionBehavior: "IPV4"
                useCases:
                  - useCase: "Download_Mode"
                    option: "BACKGROUND"
                    type: "GLOBAL"
              schema:
                $ref: "#/components/schemas/edgehostname-create-request"
        parameters:
          - $ref: "#/components/parameters/trait_usePrefixesHeader_PAPI-Use-Prefixes"
          - $ref: "#/components/parameters/trait_contractParamRequired_contractId"
          - $ref: "#/components/parameters/trait_groupParamRequired_groupId"
          - $ref: "#/components/parameters/trait_optionsParam_options"
    /edgehostnames/{edgeHostnameId}:
      get:
        summary: Get an edge hostname
        description: |
          This polls the state of an edge hostname, typically after [creating a new edge hostname](https://papi-akamai.readme.io/reference/edgehostnames#post_edgehostnames). The response tells you whether the CNAME has been fully distributed across the network. If the hostname's `status` is `ACTIVE`, the process is complete. Until then, you typically see values of `ZONE1`, `ZONE2`, `ZONE3`, or simply `PENDING`.
        operationId: "GET_edgehostnames-edgeHostnameId"
        responses:
          200:
            description: ""
            content:
              application/json:
                example:
                  accountId: act_1-1TJZFB
                  contractId: ctr_1-1TJZH5
                  groupId: grp_15225
                  edgeHostnames:
                    items:
                      - edgeHostnameId: ehn_887436
                        edgeHostnameDomain: "example.com.edgesuite.net"
                        productId: prd_Alta
                        domainPrefix: "example.com"
                        domainSuffix: "edgesuite.net"
                        secure: false
                        ipVersionBehavior: "IPV4"
                        useCases:
                          - useCase: "Download_Mode"
                            option: "BACKGROUND"
                            type: "GLOBAL"
                schema:
                  $ref: "#/components/schemas/edgehostname-get-response"
        parameters:
          - $ref: "#/components/parameters/trait_usePrefixesHeader_PAPI-Use-Prefixes"
          - $ref: "#/components/parameters/trait_contractParamRequired_contractId"
          - $ref: "#/components/parameters/trait_groupParamRequired_groupId"
          - $ref: "#/components/parameters/trait_optionsParam_options"
      parameters:
        - name: edgeHostnameId
          in: path
          required: true
          description: |
            Unique identifier for the edge hostname.
            See [ID prefixes](doc:id-prefixes)
            for details on omitting the value's `ehn_` prefix.
          schema:
            type: string
  components:
    schemas:
      edgehostname-create-request:
        description: |
          Specifies a set of available hostnames to which a property version may be applied. To POST a new edge hostname, specify a single object with `productId`, `domainPrefix`, and `domainSuffix` members, and optional `ipVersionBehavior` and `secure` members. Relevant response objects appear within the outer [Envelope](#envelope) object's `edgehostnames.items` array.
        type: object
        required:
          - "productId"
          - "domainPrefix"
          - "domainSuffix"
          - "ipVersionBehavior"
        properties:
          productId:
            description: |
              The product under which the edge hostname was created. See [ID prefixes](doc:id-prefixes) for details on how to omit the ID's `prd_` prefix.
            type: string
          domainPrefix:
            description: |
              The origin domain portion of the edge hostname. An edge hostname consists of a customer-specific `namePrefix` such as `www.example.com` and an Akamai-specific `domainSuffix` such as `edgesuite.net`. The edge hostname's final DNS CNAME combines the two, for example, `www.example.com.edgesuite.net`.
            type: string
          domainSuffix:
            type: string
          secure:
            type: boolean
          secureNetwork:
            description: |
              On POST, specifies the type of security for the new edge hostname. With `STANDARD_TLS` specified, specify a `domainSuffix` of `edgesuite.net`. With `SHARED_CERT` specified, specify a `domainSuffix` of `akamaized.net`. With `ENHANCED_TLS` specified, you need to specify a `certEnrollmentId` value along with a `domainSuffix` of `edgekey.net`.
            type: string
            enum:
              - "ENHANCED_TLS"
              - "STANDARD_TLS"
              - "SHARED_CERT"
          ipVersionBehavior:
            type: string
            enum:
              - "IPV4"
              - "IPV6_COMPLIANCE"
              - "IPV6_PERFORMANCE"
          slotNumber:
            description: |
              On POST, sets the slot number for secure ESSL properties.
            type: integer
          certEnrollmentId:
            description: |
              When creating an Enhanced TLS edge hostname, this sets the certificate enrollment ID. Specify this on POST, with `secureNetwork` set to `ENHANCED_TLS`. To obtain a value programmatically, run the Certificate Provisioning System API's [List enrollments](https://developer.akamai.com/api/core_features/certificate_provisioning_system/v2.html#getenrollments) operation. Choose the appropriate enrollment, strip the leading path expression from its `location` member, and use that value as the `certEnrollmentId`.
            type: integer
          useCases:
            maxItems: 2
            type: array
            items:
              description: |
                Optionally when configuring a new edge hostname, this assigns a preset _use case_ that characterizes the type of traffic served, to help optimize deployment over the Akamai edge network. To gather values to add to this object, run the [List use cases](https://papi-akamai.readme.io/reference/productsproductidmapping-use-cases#get_products-productid-mapping-use-cases) operation.
              type: object
              required:
                - "useCase"
                - "option"
                - "type"
              properties:
                useCase:
                  description: |
                    Uniquely identifies each mapping use case scenario. Use this to specify the same member name available in the [UseCase](#84c668bb) response object.
                  type: string
                option:
                  description: |
                    Specifies one of the available `options` available in the [UseCase](#84c668bb) response object.
                  type: string
                type:
                  description: |
                    Identifies the type of network over which traffic deploys. The only value currently available is `GLOBAL`. Use this to specify the same member name available in the [UseCase](#84c668bb) response object.
                  type: string
                  enum:
                    - "GLOBAL"
      edgehostname-get-response:
        description: |
          A common outer wrapping object structure that provides additional contextual details for a set of requested data. The data itself is available under various inner members' `items` array, even individual items. See [ID prefixes](doc:id-prefixes) for more information.
        type: object
        properties:
          accountId:
            type: string
          contractId:
            type: string
            default: SIERRA
          edgeHostnames:
            description: |
              The set of requested edge hostnames, available within an `items` array.
            type: object
            properties:
              items:
                type: array
                items:
                  description: |
                    Specifies a set of available hostnames to which a property version may be applied. To POST a new edge hostname, specify a single object with `productId`, `domainPrefix`, and `domainSuffix` members, and optional `ipVersionBehavior` and `secure` members. Set `secureNetwork` for a Standard TLS, Enhanced TLS, or a shared certificate edge hostname. Relevant response objects appear within the outer [Envelope](#envelope) object's `edgehostnames.items` array.
                  type: object
                  required:
                    - "domainPrefix"
                    - "domainSuffix"
                    - "edgeHostnameDomain"
                    - "edgeHostnameId"
                    - "ipVersionBehavior"
                    - "productId"
                    - "secure"
                  properties:
                    domainPrefix:
                      description: |
                        The origin domain portion of the edge hostname. An edge hostname consists of a customer-specific `namePrefix` such as `www.example.com` and an Akamai-specific `domainSuffix` such as `edgesuite.net`. The edge hostname's final DNS CNAME combines the two, for example, `www.example.com.edgesuite.net`.
                      type: string
                    domainSuffix:
                      description: |
                        The Akamai-specific portion of the edge hostname, for example, `edgesuite.net`.
                      type: string
                    edgeHostnameDomain:
                      description: |
                        The full edge domain name formed from the `domainPrefix` and `domainSuffix`.
                      type: string
                    edgeHostnameId:
                      description: |
                        The edge hostname's unique identifier, which can be assigned to a property. See [ID prefixes](doc:id-prefixes) for details on how to omit the ID's `ehn_` prefix.
                      type: string
                    ipVersionBehavior:
                      description: |
                        Which version of the IP protocol to use: `IPV4` for version 4 only, or `IPV6_COMPLIANCE` for both 4 and 6. The default value for requests is `IPV4`.
                      type: string
                      enum:
                        - "IPV4"
                        - "IPV6_COMPLIANCE"
                    productId:
                      description: |
                        The product under which the edge hostname was created. See [ID prefixes](doc:id-prefixes) for details on how to omit the ID's `prd_` prefix.
                      type: string
                    secure:
                      description: |
                        Set to `true` if the edge hostname is to be used with SSL. The default value for POST requests is `false`. Setting `secure:true` for new edge hostnames isn't supported.
                      type: boolean
                    status:
                      description: |
                        Appears as `PENDING` for any newly defined hostname whose DNS mapping hasn't yet been distributed across the entire Akamai network. If `status` is omitted, it indicates the edge hostname is active. Note that an edge hostname's status is unrelated to a property activation's deployment status.
                      type: string
                      enum:
                        - "PENDING"
                    mapDetails:serialNumber:
                      description: |
                        For Akamai clients, yields the serial number of the edge server that resolved the DNS record.
                      type: integer
                    mapDetails:mapDomain:
                      description: |
                        For Akamai clients, yields the domain of the edge server that resolved the DNS record.
                      type: string
                    useCases:
                      type: array
                      items:
                        type: object
                        required:
                          - "useCase"
                          - "option"
                          - "type"
                        properties:
                          useCase:
                            type: string
                          option:
                            type: string
                          type:
                            type: string
          groupId:
            type: string
      edgehostname-post-response:
        description: |
          Provides a hypermedia link to a newly created resource. The response's single member name indicates the type of resource.
        type: object
        required:
          - "edgeHostnameLink"
        properties:
          edgeHostnameLink:
            description: |
              Links the newly created edge hostname.
            type: string
    responses: {}
    parameters:
      trait_contractParamRequired_contractId:
        name: contractId
        in: query
        required: true
        description: |
          Unique identifier for the contract.
          See [ID prefixes](doc:id-prefixes)
          for details on omitting the value's `ctr_` prefix.
        schema:
          type: string
      trait_contractParamOptional_contractId:
        name: contractId
        in: query
        description: |
          Unique identifier for the contract.
          The parameter is optional if the property has been
          provisioned under only one contract.
          Otherwise you need to specify it along with the `groupId`.
          (In other operations that don't specify a `propertyId` URL
          parameter, this parameter is always required.)
          See [ID prefixes](doc:id-prefixes)
          for details on omitting the value's `ctr_` prefix.
        schema:
          type: string
      trait_contractParamOptionalBulk_contractId:
        name: contractId
        in: query
        description: |
          Optionally filters bulk searches to properties provisioned
          under the specified contract. For bulk operations, you can
          specify `contractId` and `groupId` independently from each
          other.
        schema:
          type: string
      trait_groupParamRequired_groupId:
        name: groupId
        in: query
        required: true
        description: |
          Unique identifier for the group.
          See [ID prefixes](doc:id-prefixes)
          for details on omitting the value's `grp_` prefix.
        schema:
          type: string
      trait_groupParamOptional_groupId:
        name: groupId
        in: query
        description: |
          Unique identifier for the group.
          The parameter is optional if the property has been
          provisioned under only one group.
          Otherwise you need to specify it along with the `contractId`.
          (In other operations that don't specify a `propertyId` URL
          parameter, this parameter is always required.)
          See [ID prefixes](doc:id-prefixes)
          for details on omitting the value's `grp_` prefix.
        schema:
          type: string
      trait_groupParamOptionalBulk_groupId:
        name: groupId
        in: query
        description: |
          Optionally filters bulk searches to properties provisioned
          under the specified group. For bulk operations, you can
          specify `contractId` and `groupId` independently from each
          other.
        schema:
          type: string
      trait_optionsParam_options:
        name: options
        in: query
        description: |
          Comma-separated list of options to enable; `mapDetails`
          enables extra mapping-related information.
        schema:
          type: string
      trait_validateHostnamesParam_validateHostnames:
        name: validateHostnames
        in: query
        description: |
          When `false` (the default), skips validation tests that
          would identify potential hostname-related problems within
          the response object's `errors` and `warnings` arrays. See
          [Property hostname errors](doc:property-hostname-errors)
          for details on relevant error feedback. See
          [Fast validation, activation, and fallback](doc:fast-validation)
          for details on the delays this might avoid.
        schema:
          default: true
          type: boolean
      trait_validateRulesParam_validateRules:
        name: validateRules
        in: query
        description: |
          Set to `true` by default. When `false`, skips validation
          tests that would identify potential problems within the
          response object's `errors` and `warnings` arrays. See the
          [JSON problems](doc:json-problem-responses)
          section for details on this error feedback. See
          [Fast validation, activation, and fallback](doc:fast-validation)
          for details on the delays this might avoid.
        schema:
          default: true
          type: boolean
      trait_validateModeParam_validateMode:
        name: validateMode
        in: query
        description: |
          With `validateRules` enabled, setting this to `fast`
          performs a quick validation check based on the provided
          JSON. This is faster than the default `full` validation,
          which performs more extensive checks on the converted XML
          metadata configuration.
        schema:
          default: full
          type: string
          enum:
            - "full"
            - "fast"
      trait_dryRunParam_dryRun:
        name: dryRun
        in: query
        description: |
          With `validateRules` also enabled, allows for a _dry run_ in
          order to gather any possible errors without saving the rule
          tree.
        schema:
          default: false
          type: boolean
      trait_paginated_offset:
        name: offset
        in: query
        description: |
          For paginated responses, specifies the page of results to
          include, starting from `0`.
        schema:
          minimum: 0
          type: integer
      trait_paginated_limit:
        name: limit
        in: query
        description: |
          For paginated responses, specifies the number of results to
          include on each page.
        schema:
          minimum: 1
          type: integer
      trait_usePrefixesHeader_PAPI-Use-Prefixes:
        name: "PAPI-Use-Prefixes"
        description: |
          Sets whether to display three-letter prefixes in various ID values in response data. This may override the client's default `usePrefixes` setting. See [ID Prefixes](doc:id-prefixes).
        in: header
        required: true
        schema:
          type: string
    examples: {}
    requestBodies: {}
    headers: {}
    securitySchemes: {}
    links: {}
    callbacks: {}
